config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  root "jobs#index"
  

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		@jobs = Job.all.order("created_at DESC")
	end

	def show

	end

	def new
		@job = Job.new

	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else 
			render "New"
		end
	end


	def edit

	end

	def update

	end

	def destroy

	end

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url)

	end 

	
	def find_job
		@job = Job.find(params[:id])
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
	= f.input :title, label: "Job Title"
	= f.input :description, label: "Job Description"
	= f.input :company, label: "Your Company"
	= f.input :url, label: "Link to Job"
	%br/
	=f.button :submit

app/views/jobs/index.html.haml
-@jobs.each do |job|
	%h2 = job.title
	%p = job.company

= link_to "New Job", new_job_path

app/views/jobs/new.html.haml
%h1 New Job

= render 'form'

= link_to "Back", root_path

app/views/jobs/show.html.haml
%h1 = @job.title
%p = @job.description
%p = @job.company

= link_to "Home", root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobsBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>